<?php

/**
 * @file
 * Contains joecrespo.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function joecrespo_node_presave(EntityInterface $entity) {
  // Embellish the node title.
  $embellish = Drupal::service('joecrespo.embellish');
  $adjective = $embellish->describe('flower');
  $entity->set('title', t('Joe Crespo is @adjective', ['@adjective' => $adjective]));

  $notifier = Drupal::service('joecrespo.notifier');
  $notifier->send(t('Joe, there is a new post that calls you @adjective', ['@adjective' => $adjective]));
}
